const composeUniqueEventKey = (eventCategory: string, eventId: string) => eventCategory + '-' + eventId;

export const MEDICAL_EXAMINATION = 'medical-examination';

// **** FEATURE_1 ****
export const ADMIN_ADDED_APPOINTMENT = 'admin-added-appointment';
export const ADMIN_REMOVED_APPOINTMENT = 'admin-removed-appointment';
export const MEDICAL_EXAMINATION_ADMIN_ADDED_APPOINTMENT = composeUniqueEventKey(MEDICAL_EXAMINATION, ADMIN_ADDED_APPOINTMENT);
export const MEDICAL_EXAMINATION_ADMIN_REMOVED_APPOINTMENT = composeUniqueEventKey(MEDICAL_EXAMINATION, ADMIN_REMOVED_APPOINTMENT);

// **** FEATURE_2 ****
export const USER_REQUESTED_APPOINTMENTS = 'user-requested-appointments';
export const ADMIN_RECIVED_USER_REQUESTED_APPOINTMENTS = 'admin-recived-user-requested-appointments';
export const ADMIN_CONFIRMED_ONE_OF_USER_REQUESTED_APPOINTMENTS = 'admin-confirmed-one-of-user-requested-appointments';
export const ADMIN_REJECTED_ALL_OF_USER_REQUESTED_APPOINTMENTS = 'admin-rejected-all-of-user-requested-appointments';
export const MEDICAL_EXAMINATION_USER_REQUESTED_APPOINTMENTS = composeUniqueEventKey(MEDICAL_EXAMINATION, USER_REQUESTED_APPOINTMENTS);
export const MEDICAL_EXAMINATION_ADMIN_RECIVED_USER_REQUESTED_APPOINTMENTS = composeUniqueEventKey(MEDICAL_EXAMINATION, ADMIN_RECIVED_USER_REQUESTED_APPOINTMENTS);
export const MEDICAL_EXAMINATION_ADMIN_CONFIRMED_ONE_OF_USER_REQUESTED_APPOINTMENTS = composeUniqueEventKey(MEDICAL_EXAMINATION, ADMIN_CONFIRMED_ONE_OF_USER_REQUESTED_APPOINTMENTS);
export const MEDICAL_EXAMINATION_ADMIN_REJECTED_ALL_OF_USER_REQUESTED_APPOINTMENTS = composeUniqueEventKey(MEDICAL_EXAMINATION, ADMIN_REJECTED_ALL_OF_USER_REQUESTED_APPOINTMENTS);

// **** FEATURE_3 ****
export const ADMIN_GRANTED_ACCESS_TO_PSYCHOLOGICAL_EXAMINATION = 'admin-granted-access-to-psychological-examination';
export const ADMIN_DENIED_ACCESS_TO_PSYCHOLOGICAL_EXAMINATION = 'admin-denied-access-to-psychological-examination';
export const MEDICAL_EXAMINATION_ADMIN_GRANTED_ACCESS_TO_PSYCHOLOGICAL_EXAMINATION = composeUniqueEventKey(MEDICAL_EXAMINATION, ADMIN_GRANTED_ACCESS_TO_PSYCHOLOGICAL_EXAMINATION);
export const MEDICAL_EXAMINATION_ADMIN_DENIED_ACCESS_TO_PSYCHOLOGICAL_EXAMINATION = composeUniqueEventKey(MEDICAL_EXAMINATION, ADMIN_DENIED_ACCESS_TO_PSYCHOLOGICAL_EXAMINATION);